### ISSUE TITLE
flit install --symlink throws an error

### ISSUE THREAD

**Issue by quintijn** [dictation-toolbox/Vocola2#8]
This was working fine all the time, but now throws an error:

(build_package.ps1 works, and I upgraded pip to version 22.0.3)

NOTE: I am still in the makeflitinstall branch. 

Traceback (most recent call last):
  File "c:\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38-32\Scripts\flit.exe\__main__.py", line 7, in <module>
  File "c:\python38-32\lib\site-packages\flit\__init__.py", line 193, in main
    Installer.from_ini_path(args.ini_file, user=args.user, python=python,
  File "c:\python38-32\lib\site-packages\flit\install.py", line 419, in install
    self.install_with_pip()
  File "c:\python38-32\lib\site-packages\flit\install.py", line 357, in install_with_pip
    check_call(cmd, shell=shell)
  File "c:\python38-32\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\python38-32\\python.exe', '-m', 'pip', 'install', '.']' returned non-zero exit status 1.

**Comment by dougransom** [comment]
try ‘pip install flit’

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Quintijn Hoogenboom ***@***.***>
Sent: Tuesday, March 15, 2022 3:23:37 AM
To: dictation-toolbox/Vocola2 ***@***.***>
Cc: Doug Ransom ***@***.***>; Assign ***@***.***>
Subject: [dictation-toolbox/Vocola2] flit install --symlink throws an error (Issue #8)


This was working fine all the time, but now throws an error:

(build_package.ps1 works, and I upgraded pip to version 22.0.3)

NOTE: I am still in the makeflitinstall branch.

Traceback (most recent call last):
File "c:\python38-32\lib\runpy.py", line 194, in _run_module_as_main
return run_code(code, main_globals, None,
File "c:\python38-32\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Python38-32\Scripts\flit.exe_main.py", line 7, in
File "c:\python38-32\lib\site-packages\flit_init.py", line 193, in main
Installer.from_ini_path(args.ini_file, user=args.user, python=python,
File "c:\python38-32\lib\site-packages\flit\install.py", line 419, in install
self.install_with_pip()
File "c:\python38-32\lib\site-packages\flit\install.py", line 357, in install_with_pip
check_call(cmd, shell=shell)
File "c:\python38-32\lib\subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\python38-32\python.exe', '-m', 'pip', 'install', '.']' returned non-zero exit status 1.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdictation-toolbox%2FVocola2%2Fissues%2F8&data=04%7C01%7C%7C4d0e8749fbb44c9535d908da066de22a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637829366257258133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bh1JUq8UkoBitzT%2FKqhPxTOLmjUJfCvw3Wx7dtI5%2Fdc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA262USBB4OIVV2UDT657RLVABQKTANCNFSM5QYGQUXQ&data=04%7C01%7C%7C4d0e8749fbb44c9535d908da066de22a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637829366257258133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2qJvTBIlrzQOh4%2FjRJ4NGa3LrWHdQjuxqas2k5Gj200%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4d0e8749fbb44c9535d908da066de22a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637829366257258133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rtzmRrjTMeIO8txVn9NGkuhxSuvu826GP%2BlO%2BdqZt7I%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4d0e8749fbb44c9535d908da066de22a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637829366257258133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QKxhT%2Fai%2F701CzXy%2FD%2BcupffCwMDR5k3ikJ3p5n0g8c%3D&reserved=0>.

**Comment by quintijn** [comment]
Great, that worked! Thanks, Doug
